### ISSUE TITLE
Assembly Methods: RFC 10

### ISSUE THREAD

**Issue by mef51** [igemuottawa/igem-bricklayer#4]
As RFC 10 is one of the most common assembly methods, we'll start with implementing that.
- [x] Prototype of algorithm. Maybe a console program. Anything that takes inputs and give outputs

**Comment by jmsleiman** [comment]
I thought were were assigning this to Peter Doan?

(I would say this issue would be more create the functions, test them, and forget about I/O as much as possible.)

**Comment by pdoan017** [comment]
I just pushed the complete function for RFC 10

**Comment by mef51** [comment]
The code looks good. We'll have to intergrate into the app eventually but it works so I'm closing this issue
