### ISSUE TITLE
Scrape as much BioBrick data off the partsregistry site and store it locally on our own server

### ISSUE THREAD

**Issue by mef51** [igemuottawa/igem-bricklayer#7]
("Scraping" a website means reading a webpage and storing specific information from it. In this case, since there's so much info, we write a script to do the reading and the storing.)

Currently, every time someone searches through our app, We fire off tons of requests very quickly to the partsregistry site. 

This is rude because:
1. We rely on **them** storing the data **we** need for **our** app to work. They're paying, we're benefiting. They expose the information, yes, but the problem is not that we are accessing their information; the problem is that we continuously access the same information repeatedly. Our app strains their server. 
2. We are using our app to access parts of their site that they don't want us to access, based on their [robots.txt](http://parts.igem.org/robots.txt)

This is bad because:
1. We are dependent on their database. If their site goes down, our app goes down.
2. If they ever notice our app generating a lot of traffic on their site, they have every right to block our IP and suddenly search won't work anymore and our app becomes unusable.

The solution is to scrape all the information we need and store it locally on our own machine. 

This is good because:
1. We're not assholes anymore: We're paying, we're benefiting
2. If their site goes down, the app is still usable.
3. We only access the information from partsregistry a single time ever, and not every time someone does a search.

What if our copy of all the information becomes out of date?
We can run our scraping script once every week, or month, or whenever we feel like. This is fine because we're not putting consistent strain on the partsregistry site. Moreover we can set it up so scraping happens slowly, to put even less strain on partsregistry.

Scraping is the long term solution to this problem. For now, let's get a prototype of the app working using the rude way of searching.

**Comment by jmsleiman** [comment]
Agreed, please split the task down into sub-bugs/feature requests when you are ready so we can assign them independently and hopefully speed it up.
